name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run standard linting and tests on root of project
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test
    
      - name: Run tests for workers
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test --workspace=apps/workers